//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mordor_Simple.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MordorEntities : DbContext
    {
        public MordorEntities()
            : base("name=MordorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Horde> Hordes { get; set; }
        public virtual DbSet<Orc> Orcs { get; set; }
        public virtual DbSet<Race> Races { get; set; }
        public virtual DbSet<Weapon> Weapons { get; set; }
    }
}
