//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mordor_Simple.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orc
    {
        public long OrcId { get; set; }
        public string Name { get; set; }
        public Nullable<long> KillCount { get; set; }
        public long RaceId { get; set; }
        public Nullable<long> WeaponId { get; set; }
        public long HordeId { get; set; }
    
        public virtual Horde Horde { get; set; }
        public virtual Race Race { get; set; }
        public virtual Weapon Weapon { get; set; }
    }
}
